[project]
name = "spotidex-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi-cli>=0.0.28",
    "fastapi[standard]>=0.103.2",
    "mutagen>=1.48.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "spotdl>=4.5.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
]
